[package]
name = "tio"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-task = "1.3.1"
crossbeam-utils = "0.7.2"
crossbeam-deque = "0.7.3"
futures = "0.3.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "task"
path = "benches/task.rs"
harness = false
