on: [push, pull_request]
name: Benchmark
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Benchmark
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --all-features
